### ISSUE TITLE
ModuleNotFoundError: No module named 'babel.numbers'

### ISSUE THREAD

**Issue by digulla** [trustin/sphinx-maven-plugin#14]
When running version 0.3.0 of the plugin on Windows, I get this error:

    ModuleNotFoundError: No module named 'babel.numbers'

Any ideas why it finds babel.dates but not babel.numbers?

This is the full log:

```
# Sphinx version: 1.7.4
# Python version: 3.6.4 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10
# Last messages:
#   building [mo]: targets for 0 po files that are out of date
#
#   building [html]: targets for 1 source files that are out of date
#
#   updating environment:
#
#   1 added, 0 changed, 0 removed
#
#   reading sources... [100%] index
#
# Loaded extensions:
#   alabaster (0.7.10) from C:\tools\cygwin\tmp\_MEI171802\alabaster\__init__.pyc
#   sphinx.ext.autodoc (1.7.4) from C:\tools\cygwin\tmp\_MEI171802\sphinx\ext\autodoc\__init__.pyc
#   sphinx.ext.doctest (1.7.4) from C:\tools\cygwin\tmp\_MEI171802\sphinx\ext\doctest.pyc
#   sphinx.ext.todo (1.7.4) from C:\tools\cygwin\tmp\_MEI171802\sphinx\ext\todo.pyc
#   sphinx.ext.coverage (1.7.4) from C:\tools\cygwin\tmp\_MEI171802\sphinx\ext\coverage.pyc
#   sphinx.ext.mathjax (1.7.4) from C:\tools\cygwin\tmp\_MEI171802\sphinx\ext\mathjax.pyc
#   sphinx.ext.ifconfig (1.7.4) from C:\tools\cygwin\tmp\_MEI171802\sphinx\ext\ifconfig.pyc
#   sphinx.ext.viewcode (1.7.4) from C:\tools\cygwin\tmp\_MEI171802\sphinx\ext\viewcode.pyc
#   sphinx.ext.graphviz (1.7.4) from C:\tools\cygwin\tmp\_MEI171802\sphinx\ext\graphviz.pyc
Traceback (most recent call last):
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\cmdline.py", line 304, in main
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\application.py", line 331, in build
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\builders\__init__.py", line 338, in build_update
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\builders\__init__.py", line 351, in build
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\environment\__init__.py", line 565, in update
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\environment\__init__.py", line 584, in _read_serial
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\environment\__init__.py", line 659, in read_doc
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\io.py", line 294, in read_doc
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\docutils\core.py", line 218, in publish
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\docutils\core.py", line 199, in apply_transforms
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\transforms\__init__.py", line 96, in apply_transforms
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\docutils\transforms\__init__.py", line 171, in apply_transforms
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\transforms\__init__.py", line 128, in apply
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\util\i18n.py", line 244, in format_date
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\util\i18n.py", line 206, in babel_format_date
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\dates.py", line 738, in format_datetime
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\dates.py", line 1232, in apply
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\dates.py", line 1229, in __mod__
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\dates.py", line 1254, in __getitem__
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\dates.py", line 1343, in format_month
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\dates.py", line 331, in get_month_names
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\core.py", line 650, in months
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\core.py", line 364, in _data
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\localedata.py", line 111, in load
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\babel\localedata.py", line 117, in load
ModuleNotFoundError: No module named 'babel.numbers'

```

**Comment by jakubhava** [comment]
@trustin @digulla  I can confirm that, having the same issue. Works on the sphinx-gradle plugin 1.1.0

**Comment by trustin** [comment]
Seems like the shipped Sphinx binary does not contains `babel.numbers`. I didn't get such error for my Sphinx site though. Perhaps there's a certain extension that triggers this? Will try to fix in the next release.

**Comment by jakubhava** [comment]
Amazing, thanks a lot. I'm happy to help out with testing, just let me know. Thanks for great plugin!

**Comment by trustin** [comment]
@jakubhava reported that the problem is gone after updating to 2.2.3 - https://github.com/trustin/sphinx-gradle-plugin/issues/11
